# INSTALLING AND IMPORTING PACKAGES
# %%capture
# %pip install numpy==2.3.4
# %pip install matplotlib==3.10.7
# %pip install ibm-watsonx-ai==1.4.7

import numpy as np
import matplotlib.pyplot as plt
import json
import os
from ibm_watsonx_ai import Credentials
from ibm_watsonx_ai.foundation_models import ModelInference
from ibm_watsonx_ai.metanames import GenTextParamsMetaNames as GenParams
from ibm_watsonx_ai.foundation_models.utils.enums import ModelTypes, DecodingMethods

# Libraries and codes to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/1r_mM6ZPYNxcFv65QkzubA/California-Culinary-Map.txt

# STEP 1: LOAD THE DATA

### 1.1: Define the file_path to the text file
file_path = "California-Culinary-Map.txt"

### 1.2: Open the text file
with open(file_path, "r", encoding = "utf-8") as file:
    restaurant_data = file.read()

### 1.3: Print the first 100 characters of the restaurant data
print(restaurant_data[:100])

# STEP 2: SPLIT THE RESTAURANT PARAGRAPHS INTO A PYTHON LIST

### 2.1: Split the restaurant paragraphs into list (hint: use .split)
restaurant_list = restaurant_data.split("\n\n")

### 2.2: Since the first item is the dataset name, we remove it
restaurant_list = restaurant_list[1:]

### 2.3: Print out the number of restaurants we have
print("Number of restaurants:", len(restaurant_list))

### 2.4: Print out the first item to have a closer look at the content
print(restaurant_list[0])

# STEP 3: IMPLEMENT THE LLM FUNCTION
def llm_model(system_msg, prompt_txt):
    model_id = "ibm/granite-4-h-small"
    project_id = "skills-network"
    credentials = Credentials(url = "https://us-south.ml.cloud.ibm.com")

    ### 3.1: Define the model by ModelInference
    model = ModelInference(model_id = model_id,
                           credentials = credentials,
                           project_id = project_id)

    ### 3.2: Define the messages
    messages = [{"role": "system", "content": system_msg},
                {"role": "user", "content": prompt_txt}]

    ### 3.3: Get the final response output and return it
    response = model.chat(messages = messages)
    return response["choices"][0]["message"]["content"]

# STEP 4: TESTING THE LLM MODEL
import time

def safe_llm_call(system_msg, prompt_txt, retries = 3):
    for i in range(retries):
        try:
            return llm_model(system_msg, prompt_txt)
        except Exception:
            time.sleep(2)
    return "Failed after retries"

system_msg = "You are a helpful assistant."
prompt_txt = "Which place is warmer in winter? Hawaii or Greenland?"
print(safe_llm_call(system_msg, prompt_txt))

# STEP 5: PROMPT ENGINEERING
EXAMPLE_RESTAURANT_PARAGRAPH = restaurant_list[1]
EXAMPLE_OUTPUT = """{{"name": "Mar de Cortez",
                      "location": "Santa Monica",
                      "type": "casual taqueria",
                      "food_style": "Baja-style seafood",
                      "rating": 4.2,
                      "price_range": 1,
                      "signatures": ["beer-battered snapper tacos", "zesty octopus ceviche"],
                      "vibe": "salt-air energy",
                      "environment": "a premier sun-drenched spot for open-air dining near the pier."
                      "shortcomings": []}}"""

def restaurant_data_structure_prompt_generation(restaurant_paragraph):
    base_system_msg = f"""You are a data extraction assistant.
                          Your task is to extract restaurant information from an unstructured restaurant description
                          and convert it into a structured JSON object.

                          Rules:
                          - Return ONLY valid JSON.
                          - Do not include explanations, markdown, or extra text.
                          - Extract the following fields: name, location, type, food_style, rating, price_range, signatures, vibe, environment, shortcomings
                          - Convert the price range into an integer equal to the number of dollar signs.
                            Examples: $ -> 1, $$ -> 2, $$$ -> 3, $$$$ -> 4
                          - signatures must be returned as a list of signature dishes.
                          - shortcomings must be returned as a list.
                          - If no shortcomings are mentioned, return an empty list.
                          - rating should be returned as a numeric value."""

    base_user_prompt = f"""Task: Convert the restaurant description below into the specified JSON format.
                           Restaurant description: {restaurant_paragraph}
                           Example:
                           Input Restaurant Description: {EXAMPLE_RESTAURANT_PARAGRAPH}
                           Output: {EXAMPLE_OUTPUT}"""

    return base_system_msg, base_user_prompt

# STEP 6: TESTING THE PROMPTS
restaurant_paragraph = restaurant_list[0]
base_system_msg, base_user_prompt = restaurant_data_structure_prompt_generation(restaurant_paragraph = restaurant_paragraph)
test_response = llm_model(system_msg = base_system_msg, prompt_txt = base_user_prompt)
print(test_response)

# Validating The LLM Outputs
from pydantic import BaseModel, Field, ValidationError
from typing import List, Optional

### 6.1: Define the schema
class Restaurant(BaseModel):
    name: str
    location: str
    type: str
    food_style: str
    rating: Optional[float] = None
    price_range: Optional[int] = None
    signatures: List[str] = Field(default_factory = list)
    vibe: Optional[str] = None
    environment: str
    shortcomings: List[str] = Field(default_factory = list)

### 6.2: Use the validation method to validate the test_response from the unit test
try:
    restaurant_data = Restaurant.model_validate_json(test_response)
    print(f"Success! Validated: {restaurant_data.name}")
except ValidationError as e:
    print(f"Validation failed: {e.json()}")

# STEP 7: STRUCTURE THE RESTAURANT DATA

# Define prompts to have an LLM that auto repairs outputs to JSON format
def JSON_auto_repair_prompts(candidate_json_output, error_message):

    auto_repair_system_msg = """You are a strict JSON correction engine.
                                Your only task is to fix invalid or malformed JSON so that it becomes valid, schema-compliant JSON.
            
                                Rules:
                                - Output ONLY valid JSON. No explanations, no markdown, no extra text.
                                - Preserve as much of the original content as possible.
                                - Do NOT invent new information unless required to fix structural/schema issues.
                                - Follow the schema implied by the validation error message.
                                - Fix common issues such as:
                                  - Missing commas, brackets, or quotes
                                  - Incorrect data types (e.g., string vs number)
                                  - Extra trailing commas
                                  - Incorrect nesting or structure
                                - Ensure final output is parseable by a standard JSON parser.
                                """

    auto_repair_prompt = f"""You are given:
                             1. A candidate JSON output that failed validation: {candidate_json_output}
                             2. The validation error message: {error_message}

                             Task:
                             - Carefully analyze the error message to identify what is wrong.
                             - Repair the JSON so that it fully conforms to the required format.
                             - Keep all valid data unchanged unless it violates the schema.
                             - Return ONLY the corrected JSON output.
                            
                             Do NOT include any commentary or explanation.
                             Return only valid JSON."""

    return auto_repair_system_msg, auto_repair_prompt

# Run the for loop to go over all the restaurant data in the list
import json
from pydantic import ValidationError

structured_restaurant_lists = []

for i, restaurant_paragraph in enumerate(restaurant_list):
    ### 7.1: Initial LLM generation (use your prompt function)
    system_msg, user_prompt = restaurant_data_structure_prompt_generation(restaurant_paragraph)
    output = llm_model(system_msg = system_msg, prompt_txt = user_prompt)
  
    ### 7.2: Validation + Auto-repair loop (Pydantic-based)
    max_retries = 3
    retry = 0
    while retry < max_retries:
        try:
            restaurant_obj = Restaurant.model_validate_json(output)
            break
        except ValidationError as e:
            error_message = e.json()
            repair_system_msg, repair_prompt = JSON_auto_repair_prompts(candidate_json_output = output, error_message = error_message)
            output = llm_model(system_msg = repair_system_msg, prompt_txt = repair_prompt)
            retry += 1

    ### 7.3: Append final structured result
    try:
        structured_restaurant_lists.append(Restaurant.model_validate_json(output).model_dump_json())
    except ValidationError:
        structured_restaurant_lists.append({"error": "unparseable_json", "raw_output": output})

    # Tracking Progress (Every 20 restaurants)
    if (i + 1) % 20 == 0:
        print(f"{i+1} out of {len(restaurant_list)} is done")

print("ALL DONE!!")

# STEP 8: SAVE THE LIST INTO A JSON FILE
if len(structured_restaurant_lists) >= 50:
    print(structured_restaurant_lists[49])
else:
    print("Less than 50 items in the list")

structured_restaurant_lists_json = [json.loads(response) for response in structured_restaurant_lists]

# For each item in the restaurant list, assign it with an itemId to be consistent with the one in the user review data
for i, response in enumerate(structured_restaurant_lists_json):
    response['itemId'] = 1000001 + i
    structured_restaurant_lists_json[i] = response
    
filename = 'structured_restaurant_data.json'
with open(filename, 'w', encoding = 'utf-8') as f:
    json.dump(structured_restaurant_lists_json, f, indent = 4)
