%%capture
%pip install numpy==2.3.4
%pip install matplotlib==3.10.7
%pip install ibm-watsonx-ai==1.4.7

import numpy as np
import matplotlib.pyplot as plt
import json
import os
from PIL import Image

# IBM WatsonX imports
from ibm_watsonx_ai import Credentials
from ibm_watsonx_ai.foundation_models import ModelInference
from ibm_watsonx_ai.metanames import GenTextParamsMetaNames as GenParams
from ibm_watsonx_ai.foundation_models.utils.enums import ModelTypes, DecodingMethods

# Libraries and codes to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/hpTjb6liKBLVHQK0UgMi5A/Recipes.json
!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/fQUs9wQ6aB6ts6fmkD2V2w/Synthetic-User-Reviews.json
!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/5_Rr6ohviItzucyWk6nkrw/synthetic-recipe-images.zip

import zipfile

with zipfile.ZipFile("synthetic-recipe-images.zip", 'r') as zip_ref:
    zip_ref.extractall()

# EXERCISE 1: Preprocess the food reciepe data¶
# Step 1: Explore the food recipe JSON File and its images

# Step 1.1: Load the JSON file
json_file = None
for file in os.listdir():
    if file.endswith(".json"):
        json_file = file
        break

with open(json_file, "r", encoding = "utf-8") as f:
    recipe_data = json.load(f)

# Step 1.2: Print key-value pairs of first recipe
first_recipe = recipe_data[0]
for key, value in first_recipe.items():
    print(f"{key} ({type(value)}): {value}")

# Step 1.3: Show image of first recipe
image_folder = "synthetic_recipe_images"
recipe_id = first_recipe["id"]
img_path = os.path.join(image_folder, f"recipe{recipe_id}.png")

if os.path.exists(img_path):
    img = Image.open(img_path)
    display(img)
else:
    print("Image not found:", img_path)

# Step 2: Define the vision LLM with LLaMA

import base64
from ibm_watsonx_ai.foundation_models import ModelInference
from ibm_watsonx_ai import Credentials

def vision_llm(system_msg, prompt_txt, image_path):
    model_id = 'meta-llama/llama-4-maverick-17b-128e-instruct-fp8'
    project_id = "skills-network"
    credentials = Credentials(url = "https://us-south.ml.cloud.ibm.com")
    generate_params = {"max_tokens": 300}

    ### Step 2.1: Define the model by ModelInference
    model = ModelInference(model_id = model_id,
                           credentials = credentials,
                           project_id = project_id,
                           params  = generate_params)

    ### Step 2.2: Encode the input image to a base64 string
    with open(image_path, "rb") as img_file:
        img_base64 = base64.b64encode(img_file.read()).decode("utf-8")

    ### Step 2.3: Define the messages for the model
    messages = [{"role": "system", "content": system_msg},
                {"role": "user", "content": [{"type": "text", "text": prompt_txt},
                                             {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{img_base64}"}}]}]

    ### Step 2.4: Get the response for the messages
    response = model.chat(messages = messages)

    return response["choices"][0]["message"]["content"]

# Step 3: Design and validate prompts for the vision LLM

def image_caption_prompt_template(food_name):
    # Step 3.1: Design the prompts
    image_caption_system_msg = """You are an expert food image analyst.
                                  Your task is to generate accurate, concise, and visually grounded descriptions of food images.
                                  Focus only on what is visible in the image. Do not guess ingredients or cooking steps that are not clearly observable."""

    image_caption_prompt_txt = f"""Analyze the food image carefully and generate a high-quality caption.
                                   The expected dish is: {food_name}

                                   Your caption must:
                                   - Describe the dish appearance (color, texture, arrangement, plating)
                                   - Identify visible ingredients only
                                   - Mention cooking style if clearly inferable (e.g., baked, fried, grilled)
                                   - Be concise (2–4 sentences max)
                                   - Avoid speculation or assumptions not supported by the image

                                   Return only the caption."""

    return image_caption_system_msg, image_caption_prompt_txt

# Step 3.2: Get prompts
system_msg, prompt_txt = image_caption_prompt_template(first_recipe["name"])

# Step 3.3: Get response from vision model
image_path = f"synthetic_recipe_images/recipe{first_recipe['id']}.png"
response = vision_llm(system_msg, prompt_txt, image_path)
print(response)

# Step 4: Caption all images and augment the data

for i in range(len(recipe_data)):
    if (i + 1) % 20 == 0:
        print(f"{i+1} out of {len(recipe_data)} is done")

    # Step 4.1: Get prompts using recipe name
    system_msg, prompt_txt = image_caption_prompt_template(recipe_data[i]["name"])
    image_path = f"synthetic_recipe_images/recipe{recipe_data[i]['id']}.png"

    # Step 4.2: Get caption from vision model
    try:
        response = vision_llm(system_msg, prompt_txt, image_path)
    except Exception as e:
        print(f"Error at index {i}, recipe_id {recipe_data[i]['id']}: {e}")
        response = "Caption generation failed"

    recipe_data[i]["image_description"] = response
print("ALL DONE!")

# Step 5: Save the image-caption-augmented recipe data
filename = 'augmented_food_recipe.json'
with open(filename, 'w', encoding = 'utf-8') as f:
    json.dump(recipe_data, f, indent = 4)

# EXERCISE 2: Preprocess the user visit history
# Step 1: Load the user review data
import json
import ast
import requests
from PIL import Image
from IPython.display import display

# Step 1.1: Load the review dataset
with open("Synthetic-User-Reviews.json", "r", encoding = "utf-8") as f:
    user_review_data = json.load(f)

# Step 1.2: Print first review key-value pairs
first_review = user_review_data[0]
for key, value in first_review.items():
    print(f"{key} ({type(value)}): {value}")

# Step 1.3: Convert string representation of list to actual Python list
image_list = ast.literal_eval(first_review["images"])

# Take the first image URL
image_url = image_list[0]

# Step 1.4: Request image content from URL
response = requests.get(image_url)

# Step 1.5: Write image content to temporary file
temp_image_path = "review_image_placeholder.jpg"

with open(temp_image_path, "wb") as f:
    f.write(response.content)

# Step 1.6: Open and display image
img = Image.open(temp_image_path)
display(img)

# Step 2: Define the prompt and the validation

# Step 2.1: Prompt template function
def review_context_image_caption_prompt_template(reviews):
    review_context_image_caption_system_msg = """You are a culinary expert and multimodal food analyst.
                                                 Your task is to generate a concise and accurate description of a food image, using both:
                                                 1. Visual information from the image
                                                 2. Context from user reviews
                                                 You must ensure the final description is consistent with the sentiment and details mentioned in the reviews.
                                                 Do not invent details not supported by either the image or the reviews."""

    review_context_image_caption_prompt_txt = f"""You are given:
                                                  - A food image
                                                  - User review context about the dish
                                                  User reviews: {reviews}

                                                  Task: Write a concise 2–4 sentence description of the food image that:
                                                  - Matches what is visible in the image
                                                  - Aligns with the sentiment expressed in the reviews
                                                  - Highlights key ingredients, presentation, and dining experience cues if relevant
                                                  - Avoids hallucination or adding unsupported details

                                                  Return only the final description."""

    return review_context_image_caption_system_msg, review_context_image_caption_prompt_txt

# Step 2.2: Get reviews text (combine title + review text for richer context)
reviews_text = first_review["title"] + ". " + first_review["text"]
system_msg, prompt_txt = review_context_image_caption_prompt_template(reviews_text)
image_list = ast.literal_eval(first_review["images"])
image_url = image_list[0]

# Save image locally
img_data = requests.get(image_url).content
image_path = "review_test_image.jpg"
with open(image_path, "wb") as f:
    f.write(img_data)

# Step 2.3: Run vision LLM
response = vision_llm(system_msg, prompt_txt, image_path)
print(response)



from tenacity import retry, stop_after_attempt, wait_exponential
import ast
import requests

### URL Request function with Retry
@retry(stop=stop_after_attempt(10), wait=wait_exponential(multiplier=1, min=1, max=10))
def get_data_with_retry(url):
    response = requests.get(url, timeout=5)
    response.raise_for_status()
    return response


### Start the for loop
for i in range(len(user_review_data)):

    # Step 3.1: Convert string → Python list
    review_images = ast.literal_eval(user_review_data[i]["images"])
    review_image_captions = []

    if len(review_images) > 0:
        for img_url in review_images:
            try:
                # Step 3.2: Fetch image with retry
                image_data = get_data_with_retry(img_url)
                print("Success!")

            except Exception as e:
                print(f"All retries failed at url {img_url}:", e)
                continue

            image_bytes = image_data.content
            with open('review_image_placeholder.jpg', 'wb') as img_file:
                img_file.write(image_bytes)

            # Step 3.3: Prompt + vision LLM call
            # Combine review context
            review_text = (user_review_data[i]["title"] + ". " + user_review_data[i]["text"])
            system_msg, prompt_txt = review_context_image_caption_prompt_template(review_text)
            response = vision_llm(system_msg, prompt_txt, "review_image_placeholder.jpg")
            review_image_captions.append(response)

    # Save captions into dataset
    user_review_data[i]["image_captions"] = review_image_captions
  
print("ALL DONE!")

# Step 4: Save the image-caption-augmented user review data
filename = 'augmented_user_review.json'
with open(filename, 'w', encoding = 'utf-8') as f:
    json.dump(user_review_data, f, indent = 4)
