# INSTALLING AND IMPORTING PACKAGES
# pip install virtualenv 
# virtualenv my_env
# source my_env/bin/activate

# python3.11 -m pip install ibm-watsonx-ai==1.0.4 \
# ibm-watson-machine-learning==1.0.357 \
# langchain==0.2.1 \
# langchain-ibm==0.1.7 \
# langchain-experimental==0.0.59 \
# mysql-connector-python==8.4.0

# wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/Mauh_UvY4eK2SkcHj_b8Tw/chinook-mysql.sql

# Use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

from ibm_watsonx_ai.foundation_models import ModelInference
from ibm_watsonx_ai.metanames import GenTextParamsMetaNames as GenParams
from ibm_watsonx_ai.foundation_models.utils.enums import ModelTypes
from ibm_watson_machine_learning.foundation_models.extensions.langchain import WatsonxLLM
from langchain_community.utilities.sql_database import SQLDatabase
from langchain_community.agent_toolkits import create_sql_agent

model_id = 'ibm/granite-3-2-8b-instruct'

parameters = {GenParams.MAX_NEW_TOKENS: 256, GenParams.TEMPERATURE: 0.5}
credentials = {"url": "https://us-south.ml.cloud.ibm.com"}
project_id = "skills-network"

model = ModelInference(model_id = model_id, params = parameters, credentials = credentials, project_id = project_id)
granite_llm = WatsonxLLM(model = model)
print(granite_llm.invoke("What is the capital of Ontario?"))

