# INSTALLING AND IMPORTING PACKAGES
# %%capture
# !pip install --user "ibm-watsonx-ai==0.2.6"
# !pip install --user "langchain==0.1.16" 
# !pip install --user "langchain-ibm==0.1.4"
# !pip install --user "langchain-experimental==0.0.57"
# !pip install --user "matplotlib==3.8.4"
# !pip install --user "seaborn==0.13.2"

# You can use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

from ibm_watsonx_ai.foundation_models import Model
from ibm_watsonx_ai.metanames import GenTextParamsMetaNames as GenParams
from ibm_watson_machine_learning.foundation_models.extensions.langchain import WatsonxLLM
from langchain_experimental.agents.agent_toolkits import create_pandas_dataframe_agent
import matplotlib.pyplot as plt
import pandas as pd

# Loading The Dataset
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/ZNoKMJ9rssJn-QbJ49kOzA/student-mat.csv")
df.head(5)
df.info()

# Loading The LLM
credentials = {"url" : "https://us-south.ml.cloud.ibm.com"}
model_id = 'mistralai/mistral-small-3-1-24b-instruct-2503'
params = {GenParams.MAX_NEW_TOKENS: 256, GenParams.TEMPERATURE: 0}
project_id = "skills-network"
space_id = None
verify = False

# Launch a watsonx.ai model
model = Model(model_id = model_id, credentials=credentials, params = params, project_id = project_id, space_id = space_id, verify = verify)
llm = WatsonxLLM(model = model)
agent = create_pandas_dataframe_agent(llm, df, verbose = False, return_intermediate_steps = True, handle_parsing_errors = True)

response = agent.invoke("how many rows of data are in this file?")
print(response["output"])
len(df)

# Returning Some Data From The LLM
response = agent.invoke("Give me all the data where student's age is over 18 years old.")
print(response)

# Task 1: Generating a first visual on the data set to know the total number of male and female students in the data set.
response = agent.invoke("Generate a bar chart to plot the gender count.")

# Task 2: Generating a pie chart to display the average value of weekend alcohol for each gender in the dataset.
response = agent.invoke("Generate a pie chart to display average value of Walc for each Gender.")

# Task 3: Exploring the impact of free time on grades based on the data.
response = agent.invoke("Create box plots to analyze the relationship between 'freetime' (amount of free time) and 'G3' (final grade) across different levels of free time.")

# Task 4: Exploring the effect of alcohol consumption on academic performance.
response = agent.invoke("Generate scatter plots to examine the correlation between 'Dalc' (daily alcohol consumption) and 'G3', and between 'Walc' (weekend alcohol consumption) and 'G3'.")

# Task 5: Relationship between parental education level and student grades
response = agent.invoke("Generate scatter plots showing the relationship between 'Medu' (mother's education level) and 'G3' (final grade), and between 'Fedu' (father's education level) and 'G3'. ")

# Task 6: Impact of internet access at home on grades
response = agent.invoke("Use bar plots to compare the average final grades ('G3') of students with internet access at home versus those without ('internet' column).")
